- .github/workflows/Windows_release.yml
- .github/workflows/pr_validation.yml
- .nuke/build.schema.json
- build/Build.CI.GitHubActions.cs
- build/Build.cs
- src/Directory.Build.props
Ported over changes in the `Petabridge.Library` template
> Update build system

- RELEASE_NOTES.md
- src/Akka.Cluster.Hosting/AkkaClusterHostingExtensions.cs
- src/Directory.Build.props
Removed all `Cluster.Sharding` methods that rely on `ClusterShardingSettings`, since it's not practical to create those prior to starting the `ActorSystem`.
> removed `ClusterShardingSettings` from sharding extensions

- src/Akka.Persistence.SqlServer.Hosting/AkkaPersistenceSqlServerHostingExtensions.cs
Small layout change to make the code more readable, removed tabs and uses same interpolation syntax as the journal part.
> cleanup WithSqlServerPersistence style

- RELEASE_NOTES.md
- Added `Akka.Persistence.PostgreSql.Hosting` NuGet package to support Postgres users.
> Added v0.1.5 Release Notes

- src/Akka.Hosting.Tests/DISanityCheckSpecs.cs
- src/Akka.Hosting.Tests/SerializerRegistrationSpecs.cs
Adding some checks to make sure we're not doing any funny stuff with the creation of `IServiceProvider` instances while the `IServiceCollection` is still being built.
> added DI sanity check specs

- src/Akka.Hosting.Tests/DISanityCheckSpecs.cs
- src/Akka.Hosting/AkkaConfigurationBuilder.cs
- src/Akka.Hosting/AkkaHostedService.cs
- src/Akka.Hosting/AkkaHostingExtensions.cs
- src/Directory.Build.props
This fixes a bug I noticed while adding Akka.Hosting support to [Phobos](https://phobos.petabridge.com/)
https://twitter.com/Aaronontheweb/status/1512497162948595717 - this turned out to be caused by Akka.Hosting calling `ServiceCollection.BuildProvider()` in multiple instances - which causes the service registration delegates to be called multiple times, thus the version of a dependency your `ActorSystem` is running with can be different than the one ASP.NET might resolve.
We've re-arranged the internals around Microsoft.Extensions.DependencyInjection inside Akka.Hosting to never actually instantiate the `IServiceProvider` ourselves - we let the runtime handle that so we end up with a consistent, single instance across the entire `IHost`.
We've also changed it such that the …
> Fixed issues with duplicate `IServiceProvider` registration

- RELEASE_NOTES.md
- src/Directory.Build.props
- [Bugfix: Fixed issues with duplicate `IServiceProvider` registration](https://github.com/akkadotnet/Akka.Hosting/pull/32), this could cause multiple instances of dependencies to be instantiated since Akka.Hosting creating multiple `IServiceProvider` instances during the construction process. This has been resolved.
> added Akka.Hosting v0.2.0 release notes

- RELEASE_NOTES.md
- src/Akka.Cluster.Hosting/AkkaClusterHostingExtensions.cs
- src/Akka.Remote.Hosting/AkkaRemoteHostingExtensions.cs
- src/Directory.Build.props
- Bugfix: when using Akka.Remote or Akka.Cluster, don't override any custom `ProviderSelection`s provided by the user.
> Don't override custom `ProviderSelection` instances

- Akka.Hosting.sln
- src/Akka.Remote.Hosting.Tests/Akka.Remote.Hosting.Tests.csproj
- src/Akka.Remote.Hosting.Tests/RemoteConfigurationSpecs.cs
- src/Akka.Remote.Hosting/AkkaRemoteHostingExtensions.cs
Fixes #36 
Added a reproduction spec for #36 and am currently working on a fix for it.
> Resolve Akka.Remote host binding issue

- RELEASE_NOTES.md
- [Bugfix: Akka.Remote.Hosting doesn't support `public-hostname` correctly](https://github.com/akkadotnet/Akka.Hosting/issues/36)
> Added 0.2.2 release notes

- README.md
- src/Akka.Hosting/ActorRegistry.cs
- src/Akka.Hosting/AkkaConfigurationBuilder.cs
- src/Akka.Hosting/AkkaHostingExtensions.cs
This PR adds both writeable and read-only interfaces for the ActorRegistry class to allow mocking in tests.
> Add interfaces for the ActorRegistry to allow mocking in tests

- src/Akka.Hosting/AkkaHostedService.cs
Fixes #48
Acquire `CoordinatedShutdown` early so it can't NRE upon acquisition from `ActorSystem` in the event of early termination. 
> close #48 - fixed source of NRE upon shutdown

- src/Akka.Hosting.Tests/ActorRegistrySpecs.cs
- src/Akka.Hosting/ActorRegistry.cs
Wanted to do this to make assertions easier to implement within the `AkkaConfigurationBuilder`.
> added throw-able `ActorRegistry.Register` method

- Akka.Hosting.sln
- src/Akka.Cluster.Hosting.Tests/Akka.Cluster.Hosting.Tests.csproj
- src/Akka.Cluster.Hosting.Tests/ClusterSingletonSpecs.cs
- src/Akka.Cluster.Hosting/AkkaClusterHostingExtensions.cs
- src/Directory.Build.props
Adding `ClusterSingletonManager` and `ClusterSingletonProxy` methods to Akka.Hosting.
Using some of the methods I originally developed here and turning them into something re-usable across end-user projects:
https://github.com/petabridge/akkadotnet-code-samples/blob/108a694421a017aadcbcc5388a98a38fe43a8f74/src/clustering/sharding-sqlserver/SqlSharding.Shared/Sharding/ProductActorProps.cs#L24-L43
> adding `ClusterSingleton` hosting methods

- RELEASE_NOTES.md
- src/Directory.Build.props
- [Add interfaces for the `ActorRegistry` to allow mocking in tests](https://github.com/akkadotnet/Akka.Hosting/pull/42)
- [Fixed: Akka.Hosting NRE upon shutdown](https://github.com/akkadotnet/Akka.Hosting/pull/49)
- [added throw-able `ActorRegistry.Register` method](https://github.com/akkadotnet/Akka.Hosting/pull/50)
- [Akka.Cluster.Hosting: adding `ClusterSingleton` hosting methods](https://github.com/akkadotnet/Akka.Hosting/pull/51)
> added 0.3.0 release notes

- src/Akka.Hosting.Tests/Akka.Hosting.Tests.csproj
- src/Akka.Hosting.Tests/DISanityCheckSpecs.cs
- src/Akka.Hosting.Tests/HoconSpecs.cs
- src/Akka.Hosting.Tests/TestHelpers.cs
- src/Akka.Hosting.Tests/test.hocon
- src/Akka.Hosting/AkkaHostingExtensions.cs
Allows Akka.Hosting to automatically load HOCON from a file. Solves a longtime painpoint for users where they typically had to call `ConfigurationFactory.ParseString(File.ReadAllText(filePath))`. Now it's a one-liner.
> added `AddHoconFile` method

- src/Akka.Cluster.Hosting.Tests/DistributedPubSubSpecs.cs
- src/Akka.Cluster.Hosting/AkkaClusterHostingExtensions.cs
Fixes #55
HOCON setting was inserted in the wrong order. Needed to add `HoconAddMode.Prepend`.
> Fix #55, wrong HOCON insertion ordering

- RELEASE_NOTES.md
- [Added common `Akka.Persistence.Hosting` package to make it easier to add `IEventAdapter`s to journals](https://github.com/akkadotnet/Akka.Hosting/issues/64).
- [Made Akka.Persistence.SqlServer.Hosting and Akka.Persistence.PostgreSql.Hosting both take a shared overload / dependency on Akka.Persistence.Hosting](https://github.com/akkadotnet/Akka.Hosting/pull/67) - did this to make it easier to add `IEventAdapter`s to each of those.
- [Add Akka.Cluster.Tools.Client support](https://github.com/akkadotnet/Akka.Hosting/pull/66) - now possible to start `ClusterClient` and `ClusterClientReceptionist`s easily from Akka.Hosting.
Fixes #
Please provide a brief description of the changes here. …
> Added v0.3.3 Release Notes

- src/Akka.Cluster.Hosting.Tests/ClusterShardingSpecs.cs
- src/Akka.Cluster.Hosting.Tests/ClusterSingletonSpecs.cs
- src/Akka.Cluster.Hosting.Tests/TestHelper.cs
- src/Akka.Cluster.Hosting/AkkaClusterHostingExtensions.cs
Adds `ActorRegistry`-capable overloads to the `WithShardRegion<TKey>` methods, which are useful in cases where my entity actors need to take a dependency on another actor reference through their constructors.
> Sharding add actor registry overloads

- RELEASE_NOTES.md
- src/Directory.Build.props
- [Adds `ActorRegistry`-capable overloads to the `WithShardRegion<TKey>` methods](https://github.com/akkadotnet/Akka.Hosting/pull/70)
> added v0.3.4 release notes

- src/Akka.Hosting.Tests/Logging/LoggerFactoryLoggerSpec.cs
Needed to call `Dispose` rather than `StopAsync`
> fixed hanging ILogger test

- src/Akka.Persistence.Hosting.Tests/Akka.Persistence.Hosting.Tests.csproj
- src/Akka.Persistence.Hosting.Tests/InMemoryPersistenceSpecs.cs
- src/Akka.Persistence.Hosting/AkkaPersistenceHostingExtensions.cs
Adds support for in-memory journal and snapshot configuration. Designed so developers can easily turn these on for testing purposes.
> added `InMemory` snapshot store and journal configuration settings

- src/Akka.Hosting/AkkaHostingExtensions.cs
Add `WithExtensions` support that simplifies adding `akka.extensions` HOCON setting
> Add `WithExtensions` support

- src/Akka.Hosting.Tests/ExtensionsSpecs.cs
- src/Akka.Hosting.Tests/XUnitLogger.cs
- src/Akka.Hosting.Tests/XUnitLoggerProvider.cs
- src/Akka.Hosting/AkkaConfigurationBuilder.cs
Improve `WithExtensions` so that it can:
- Be called multiple times without overriding each other
- Be used together along side manually declared extensions in HOCON
> Improve WithExtensions so it can be used universally

- src/Akka.Hosting/AkkaConfigurationBuilder.cs
- src/Akka.Hosting/AkkaHostingExtensions.cs
Adds `AddStartup` using `StartupTask` delegate to the configuration builder. 
This feature is useful when a user need to run a specific initialization code if anf only if the `ActorSystem` and all of the actors have been started. Although it is semantically the same as `AddActors` and `WithActors`, it disambiguate the use-case with a guarantee that it will only be executed after everything is ready.
For example, this feature is useful for: 
- kicking off actor initializations by using `Tell()`s once all of the actor infrastructure are in place, or
- pre-populating certain persistence data after everything is set up and running, useful for unit testing.
> Add StartupTask feature

- src/Akka.Cluster.Hosting.Tests/Lease/TestLease.cs
- src/Akka.Cluster.Hosting.Tests/Lease/TestLeaseActor.cs
- src/Akka.Cluster.Hosting.Tests/SplitBrainResolverSpecs.cs
- src/Akka.Cluster.Hosting/AkkaClusterHostingExtensions.cs
- src/Akka.Cluster.Hosting/SBR/SplitBrainResolverOption.cs
- src/Akka.Hosting/AkkaConfigurationBuilder.cs
Adds additional optional parameter to `WithClustering()` to also set up a split brain resolver for the cluster.
> Add split brain resolver configuration support to Akka.Cluster.Hosting

- src/Akka.Remote.Hosting.Tests/RemoteConfigurationSpecs.cs
- src/Akka.Remote.Hosting/AkkaRemoteHostingExtensions.cs
Make `WithRemoting` write the minimum HOCON override possible to prevent unexpected overrides of previously declared HOCON overrides
> WithRemoting should only override declared values

- src/Akka.Cluster.Hosting.Tests/Lease/TestLease.cs
- src/Akka.Cluster.Hosting.Tests/SplitBrainResolverSpecs.cs
- src/Akka.Cluster.Hosting/AkkaClusterHostingExtensions.cs
- src/Akka.Cluster.Hosting/SBR/SplitBrainResolverOption.cs
- src/Akka.Hosting/IHoconOption.cs
- src/Akka.Hosting/IOption.cs
This will be used to standardize how Akka.Hosting addresses a very common HOCON configuration pattern.
This allows for a HOCON-less programmatical setup replacement for the HOCON path used to configure the HOCON property. 
The pattern:
```text
akka.discovery.method = akka.discovery.config
akka.discovery.config {
class = "Akka.Discovery.Config.ConfigServiceDiscovery, Akka.Discovery"
}
```
Example implementation:
```csharp
// The base class for the option
public abstract class DiscoveryOptionBase : IOption
{ }
// The actual option implementation
public class ConfigOption : DiscoveryOptionBase
{
// Actual option implementation here
public Type Class => typeof(ConfigServiceDiscovery);
public string ConfigPath => "akka.discovery.config";
public void Apply(AkkaConfigurationBuilder builder, …
```
> Spec Proposal to standardize HOCON path based configuration pattern

- build/Build.cs
Current build script fails if SignClient or Nuke.GlobalTool is already installed
> Fix build script to not throw if tools are already installed

- build/Build.cs
- build/MdHelper.cs
- build/XmlHelper.cs
- Add our own markdown "parser"
- Insert a CDATA section into the XML if the input has '<' or '>' instead of sanitizing the text.
> Fix Nuke highly oppinionated XML and MD helper to our own code

- src/Akka.Cluster.Hosting.Tests/DistributedPubSubSpecs.cs
- src/Akka.Cluster.Hosting/AkkaClusterHostingExtensions.cs
- src/Akka.Hosting.Tests/ExtensionsSpecs.cs
- src/Akka.Hosting.Tests/HoconSpecs.cs
- src/Akka.Hosting/AkkaConfigurationBuilder.cs
- src/Akka.Hosting/AkkaHostingExtensions.cs
- src/Akka.Persistence.PostgreSql.Hosting/AkkaPersistencePostgreSqlHostingExtensions.cs
- src/Akka.Persistence.SqlServer.Hosting/AkkaPersistenceSqlServerHostingExtensions.cs
Fixes #134
* Change AddHocon and AddHoconFile default mode from Append to Prepend
This is a breaking change for all Akka.Hosting extension plugins
> [Breaking Change] remove default `HoconAddMode` from HOCON builders

- RELEASE_NOTES.md
* [Update Akka.NET from 1.4.45 to 1.4.46](https://github.com/akkadotnet/akka.net/releases/tag/1.4.46)
* [Remove default `HoconAddMode` value from `AddHocon` and `AddHoconFile`](https://github.com/akkadotnet/Akka.Hosting/pull/135)
In 0.5.2-beta1, the `HoconAddMode` argument in `AddHocon()` and `AddHoconFile()` extension methods are not optional anymore; you will need to declare that your HOCON will to append, prepend, or replace existing HOCON configuration. In almost all cases, unless you're adding a default configuration, you only need to use `HoconAddMode.Prepend`.
> Update RELEASE_NOTES.md for 0.5.2-beta1

- src/Akka.Hosting.Tests/ActorRegistrySpecs.cs
- src/Akka.Hosting/ActorRegistry.cs
This is designed to make it easier to debug scenarios where the `ActorRegistry` is not configured directly - please use `ActorRegistry.TryGet<T>` if you want to avoid exceptions during `IActorRef` retrieval.
This is a **breaking behavior change** but it is a useful one - and worth doing before https://github.com/akkadotnet/Akka.Hosting/issues/142
> `ActorRegistry.Get<T>` now throws when there is no entry for `T`

- src/Akka.Hosting.TestKit.Tests/TestEventListenerTests/EventFilterTestBase.cs
TestEventListenerTests is failing at this line: https://github.com/akkadotnet/Akka.Hosting/blob/491e8a1eb1bfc34844bacbaeafa582c01840a8af/src/Akka.Hosting.TestKit.Tests/TestEventListenerTests/EventFilterTestBase.cs#L50
Its not clear what is the cause of the failure, the `TestActor` was not receiving the "OK" signal from the custom `ForwardAllEventsTestEventListener` logger. Putting a guard code here to fish for possible future failure.
Add a guard around the failing line
> Guard the failing TestKit EventFilterTestBase

- Akka.Hosting.sln
- src/Akka.Cluster.Hosting/Akka.Cluster.Hosting.csproj
- src/Akka.Hosting.TestKit/Akka.Hosting.TestKit.csproj
- src/Akka.Hosting/Akka.Hosting.csproj
- src/Akka.Persistence.Hosting/Akka.Persistence.Hosting.csproj
- src/Akka.Persistence.PostgreSql.Hosting/Akka.Persistence.PostgreSql.Hosting.csproj
- src/Akka.Persistence.SqlServer.Hosting/Akka.Persistence.SqlServer.Hosting.csproj
- src/Directory.Build.props
Standardize csproj:
- LangVersion to 10.0
- Nullable to enable
- License to use PackageLicenseExpression that links directly to Apache-2.0.
The new PackageLicenseExpression tag translates to these nuspec tags:
```xml
<license type="expression">Apache-2.0</license>
<licenseUrl>https://licenses.nuget.org/Apache-2.0</licenseUrl>
```
> Standardize csproj files to use Directory.Build.props

- src/Akka.Hosting.Tests/RequiredActorSpecs.cs
- src/Akka.Hosting/ActorRegistry.cs
- src/Akka.Hosting/AkkaConfigurationBuilder.cs
This addresses one of the criticisms of Akka.Hosting we've heard from a number of current active users: the `ActorRegistry` is service location and that's a smelly pattern.
All of the work we've done on the `ActorRegistry` so far makes it feasible for us to now expose proper, strongly typed dependency injection to users who wish to integrate their Akka.NET actors with other popular technologies (i.e. ASP.NET) or even with other Akka.NET actors via Akka.DependencyInjection.
This PR introduces the `IRequiredActor<TActor>` type, which is designed to allow for real dependency injection rather than service location:
```csharp
public sealed class MyConsumer
{
private readonly IActorRef _actor;
public MyConsumer(IRequiredActor<MyActorType> actor)
{
_actor = actor.ActorRef;
}
public async …
```
> Proper Akka.NET Dependency Injection: `IRequiredActor<TActor>`

- src/Akka.Hosting.Tests/HostingExtensionsSpec.cs
- src/Akka.Hosting.Tests/Logging/LoggerConfigBuilderSpecs.cs
- src/Akka.Hosting.Tests/UtilSpec.cs
- src/Akka.Hosting/AkkaHostingExtensions.cs
- src/Akka.Hosting/AkkaOptions.cs
- src/Akka.Hosting/HoconExtensions.cs
- src/Akka.Hosting/LoggerConfigBuilder.cs
- src/Akka.Hosting/Properties/FriendsOf.cs
Fixes #106
- Add options to modify how dead letters are logged in the logger builder
- Add options to modify how actor debug messages are logged in the logger builder
- Add `WithActorAskTimeout()` extension method
> Add debug logging options and `WithActorAskTimeout()` extension method

- src/Akka.Hosting.API.Tests/verify/CoreApiSpec.ApproveCore.verified.txt
- src/Akka.Hosting.API.Tests/verify/CoreApiSpec.ApproveTestKit.verified.txt
- src/Akka.Hosting.TestKit.Tests/LoggerSpec.cs
- src/Akka.Hosting.TestKit/Internals/TestKitLoggerFactoryLogger.cs
- src/Akka.Hosting.TestKit/Properties/FriendsOf.cs
- src/Akka.Hosting.TestKit/TestKit.cs
- src/Akka.Hosting/Logging/LoggerFactoryLogger.cs
Fixes #177
The way the logger works inside Akka.Hosting and Akka.Hosting.TestKit is different. TestKit logger needs to actually listen to the event bus because it is wired manually.
- Make LoggerFactoryLogger methods virtual so it can be overriden
- Inharit LoggerFactoryLogger class in TestKit specialized logger and override the Receive method
> Fix Hosting.TestKit logging problem

- README.md
- src/Akka.Hosting.API.Tests/verify/CoreApiSpec.ApproveCore.verified.txt
- src/Akka.Hosting.Tests/UtilSpec.cs
- src/Akka.Hosting/HoconExtensions.cs
Better string to HOCON literal conversion:
- accounts for all illegal characters
- support for triple quote
- support for null
> Better string to HOCON literal conversion, accounting for all illegal characters

- src/Akka.Hosting.API.Tests/verify/CoreApiSpec.ApproveCore.verified.txt
- src/Akka.Hosting.Tests/ActorRegistrySpecs.cs
- src/Akka.Hosting/ActorRegistry.cs
- src/Directory.Build.props
Somewhat of an experiment - considering adding this to allow non-Akka.NET consumers to `await` for an `IActorRef` to be added to the `ActorRegistry` in the future. I'll be adding tests for the `ActorRegistry` overall in a separate PR but I have tested this functionality and it does work. However, I don't want to get users into the habit of explicitly awaiting everything from the registry just because we have it - all actors started via a `WithActors` delegate are guaranteed to be created _and available in the `ActorRegistry`_ before your `IHost.StartAsync` method exits, so you shouldn't need to await the `ActorRegsitry` when fetching any top-level actors created by the builder itself.
_However_, if you needed a child actor of some kind - one that is started _after_ the `IHost.StartAsync` …
> add `GetAsync` method to `ActorRegistry`

- RELEASE_NOTES.md
Version 1.0.2 introduces a new method to the `ActorRegistry.GetAsync` in order to allow users to force parts of their application to wait until a specific `IActorRef` has been started and added to the `ActorRegistry`.
```csharp
// arrange
var registry = new ActorRegistry();
// act
var task = registry.GetAsync<Nobody>();
task.IsCompletedSuccessfully.Should().BeFalse();
registry.Register<Nobody>(Nobody.Instance);
var result = await task;
// assert
result.Should().Be(Nobody.Instance);
```
This method is designed to allow users to wait via `async Task<IActorRef>` for an actor to be registered in the event that a specific `IRequiredActor<TKey>` is needed before Akka.Hosting can start the `ActorSystem` inside its `IHostedService`.
> added v1.0.2 Release Notes

- src/Akka.Hosting.Tests/Configuration/ConfigurationHoconAdapterTest.cs
- src/Akka.Hosting.Tests/UtilSpec.cs
- src/Akka.Hosting/HoconExtensions.cs
* Add escape character compatibility to string.ToHocon()
* Remove triple quote support, not needed because we now use escape characters
> Fix string.ToHocon() backslash escape character compatibility
